version: '3.8'
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: admin
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
volumes:
  mysql:
    driver: local